# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: check-encrypted
      name: Check if secret files are encrypted
      entry: ./bash check_encrypted.sh
      language: system
      files: ^.ssh/.*(?<!\.pub)$
